## This generates an ever-increasing number based on the date and build. Useful for CI\CD scenario's.
name: $(date:yyyy.M.d)$(rev:.r) 

parameters:
- name: publishPreRelease
  displayName: 'Publish pre-release package'
  type: boolean
  default: false

## GITHUB: specify the Pull Request Builds in yaml as below.
## Azure Devops: setup Pull Request Builds via "manage repositories" - "Branch Policies" in the Azure Devops UI instead. 
pr:
  branches:
    include:
    - main
    
trigger:
  branches:
    include: 
    - main
  paths:
    include: 
    - /.pipelines/*
    - /src/*
    exclude:
    - '/.vscode/*'
    - '/docs/*'
    - '/*.md'
    - '**/.editorconfig'
    - '**/.gitignore'

resources:
  repositories:
    - repository: yamlTemplates
      type: github
      name: "ArnoPeters/Starterkit_AzureDevops"
      endpoint: 'ArnoPeters'
      ref: 'refs/heads/Reorg'

variables:
  # Files included in the variables section can ONLY have a 'variables' section, nothing more.
  - template: build/authors.yml
  #- group: '#GroupName' # Groups are linked to Azure Devops -> Pipelines > Library > Variable Group. Keep secrets there instead of in the actual source. 
  
  # Other values as key-value pair, or Groups won't work. 
  # https://learn.microsoft.com/en-us/azure/devops/pipelines/library/variable-groups?view=azure-devops&tabs=yaml#use-a-variable-group
  #- name: Key 
  #  value: 'Value'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and Publish nuget package 
  jobs:
  - template: yaml/jobs/AzDOArtifacts_publishNugetPackage.yml@yamlTemplates
    parameters:
      azureArtifactsTargetFeed: 'Demo Environment (Scrum)/Packages'
      publishPreRelease: ${{ parameters.publishPreRelease }}
      buildSteps: 
      - task: UseDotNet@2
        displayName: 'Use dotnet 6'
        inputs:
          version: '6.0.x'
      - template: yaml/steps/buildAndTest.yml@yamlTemplates
        parameters:
          azureArtifactsSourceFeed: 'Demo Environment (Scrum)/Packages'
          runSettingsFile: 'src/.runsettings'

